version: '3.1'
services:

  drupal:
    build: ./
    image: drupal-8-apache
    links:
        - "mysql:mysql"
    ports:
      - 8888:80
    volumes:
      - ./modules:/opt/drupal/web/modules
      - ./profiles:/opt/drupal/web/profiles
      - ./themes:/opt/drupal/web/themes
      - ./sites:/opt/drupal/web/sites
    restart: always
  mysql:
    image: mysql
    environment:
        - MYSQL_USER=user
        - MYSQL_PASSWORD=mypassword
        - MYSQL_DATABASE=drupal
        - MYSQL_ROOT_PASSWORD=rootpass
